### PR TITLE
Seperate HTML, CSS, and JS into seperate files

### PR DESCRIPTION
**Pull request by 00ff0000red**
This PR separates the HTML document, the CSS stylesheet, and the JavaScript block into separate files.

The separation should make the project more maintainable, and readable.

Furthermore, all modern browsers are able to handle the separated files much better, ex: caching, streaming complication, background fetching, background parsing + compilation.
Sources: https://flaviocopes.com/javascript-async-defer/#with-defer-in-the-head

It also adds some other miscellaneous changes, adds a `lang` attribute to the document, fixed the JS MIME, etc.
Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript

It also moves the comment out of the document that no one will see, to somewhere where it would get more attention: the readme.
(I'm not sure if that's a good place though)

### CODE REVIEW

**Comment by Willard21** [comment]
I have a few concerns with this. The main one being that around 90% of the current users for this are on Khan Academy, where only 1 file is allowed. While other files can be loaded from off-site through jsdeliver (there's a very small list of whitelisted domains), caching becomes somewhat of a problem. It also kinda defeats the purpose of the site, which is to have the code on the page where people can read, edit, and make spin-offs of it.

If I'm going to merge this, then I'd prefer that it be converted to a Node.js project with a bundler script for compiling it into a single file. https://www.sitepoint.com/bundle-static-site-webpack/ explains how to get that set up.

**Comment by 00ff0000red** [comment]
> The main one being that around 90% of the current users for this are on Khan Academy, where only 1 file is allowed.

I can understand that concern, but maybe the solution isn't to keep everything in one file, but instead, to get Khan Academy to allow multiple files?
We could probably refer to this as a "feature request," or something of the sort.
Do you have any guess as to where we could contact their team, and query them on this?

> While other files can be loaded from off-site through jsdeliver (there's a very small list of whitelisted domains), caching becomes somewhat of a problem.

Can you elaborate on why caching is problematic for that?

> It also kinda defeats the purpose of the site, which is to have the code on the page where people can read, edit, and make spin-offs of it.

Ah, this clears up a lot, it helps put everything in perspective and explains why this wasn't done in the first place.

> If I'm going to merge this, then I'd prefer that it be converted to a Node.js project with a bundler script for compiling it into a single file.

Are there any particular reasons that you would prefer Node.js?

**Comment by Willard21** [comment]
The KA devs are currently in the middle of migrating their back end (which is apparently a few million lines of code) from Python 2 to Go, so they're not even considering any feature requests at the moment unfortunately. On top of that, they have a relatively small team that's responsible for a site with hundreds of millions of users, and the Computer Programming part of the site only has a few thousand users, so they tend focus their resources on other parts of the site.

The whitelist is handled through the page's [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) which is relatively strict.

I'm a little fuzzy on how caching actually works, but I know other people have attempted to use jsdeliver to have programs load JSON data from GitHub. If the page wasn't loaded in incognito or after deleting the cache, then it wouldn't show the most recent data.

I prefer Node because I use it daily, and already have it installed. JavaScript is my language of choice for pretty much everything. And I know that tools exist for Node to do pretty much anything related to web dev.

I don't really have a specific style I follow. I just try to stick to DRY principles as long as it doesn't affect performance. Before I released it on repl.it, almost nobody ever actually contributed. Most Khan Academy programmers don't have much or any experience with WebGL, 3D, ES6, or any web APIs. So I just haven't had any need to moderate contributions.

**Comment by 00ff0000red** [comment]
> The KA devs are currently in the middle of migrating their back end from Python 2 to Go, so they're not even considering any feature requests at the moment, unfortunately. On top of that, they have a relatively small team that's responsible for a site with hundreds of millions of users...

That, I can understand, and the second part I had already presumed. This route doesn't seem nearly as viable anymore.

> The whitelist is handled through the page's [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) which is relatively strict.

I use a fine-tuned, strict CSP on just about every project that I can, and it's effective. Got it, they've effectively got all fetches blocked, no working around that.

> I'm a little fuzzy on how caching actually works, but I know other people have attempted to use jsdeliver to have programs load JSON data from GitHub. If the page wasn't loaded in incognito or after deleting the cache, then it wouldn't show the most recent data.

Sounds backward, if they delete the cache, it should load the newest results, not the other way around.

> I don't really have a specific style I follow. I just try to stick to DRY principles as long as it doesn't affect performance.

Acknowledged.
Sinc there was that comment in the HTML:
> ...It allows us to write shader programs that run right on the GPU, which means it can run as fast as any C++ game.

Before you had said that this was intended to be a project that one could easily read the source of, and fit in one file for Khan Academy, I might've recommended actually using C++ and compiling to [Wasm](https://webassembly.org/).

> Before I released it on repl.it, almost nobody ever actually contributed.

Ha, well, Repl is a large community of younger programmers, so it wasn't surprising that a web-based Minecraft got a lot of attention.
I'm actually from Repl too: [@xxpertHacker](https://repl.it/@xxpertHacker).
> Most Khan Academy programmers don't have much or any experience with WebGL, 3D, ES6, or any web APIs. So I just haven't had any need to moderate contributions.

This is actually more general, a lot of programmers don't have experience with 3D; it's not taught that often.

If you don't have anything against it, I was actually going to try to get the JS to run in strict mode, and use something more modern, maybe ES9 or ES8 at least?

Seems like it'll have to be done without splitting the document though.

**Comment by Willard21** [comment]
About the cache, that's what I was trying to say there. Sorry it wasn't very clear lol.

I've been slowly updating to more modern syntax as I go. Version 0.3 and earlier were written in KA's processing.js environment where anything past ES5 is blocked. It wasn't until version 0.5 or so that I learned the trick to getting ES6+ to work in the webpage environment (the trick was just giving the script tag any MIME type so it wouldn't be parsed by their outdated libraries). And on that matter, see [this SO thread](https://stackoverflow.com/questions/189850/what-is-the-javascript-mime-type-for-the-type-attribute-of-a-script-tag).

I have strict mode working in my local branch where I'm adding lighting right now. That's how I knew it was only a 2 line fix.

**Comment by 00ff0000red** [comment]
> It wasn't until version 0.5 or so that I learned the trick to getting ES6+ to work in the webpage environment (the trick was just giving the script tag any MIME type so it wouldn't be parsed by their outdated libraries). And on that matter, see [this SO thread](https://stackoverflow.com/questions/189850/what-is-the-javascript-mime-type-for-the-type-attribute-of-a-script-tag).

https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages:javascript-mime-type
https://tools.ietf.org/pdf/draft-ietf-dispatch-javascript-mjs-07.pdf

The MIME should still be "text/javascript".

The real trick would be to get `<script type="module">` working after strict mode.
https://caniuse.com/es6-module

**Pull request closed without merging**
