### PR TITLE
Add Lava

### PR DESCRIPTION
**Pull request by sauron65**
Add a lava block. Does not kill you when you walk through. Does not flow and is not animated.

### CODE REVIEW

**Review by harsha7addanki — CHANGES_REQUESTED** [review]
Add an anim and burn nearby wood

**Comment by sauron65** [comment]
@harsha7addanki
> Add an anim and burn nearby wood

I have no idea how to do that. too hard.

**Comment by harsha7addanki** [comment]
you make no sense

**Comment by sauron65** [comment]
this seems like it won't be merged. I'll close in 24hrs

**Pull request closed without merging**
