### PR TITLE
Update to ES6+ (1/6)

### PR DESCRIPTION
**Pull request by 00ff0000red**
Fixes issue https://github.com/Willard21/MineKhan/issues/10

First of approximately 6 PRs.

### CODE REVIEW

**Comment by 00ff0000red** [comment]
Is it just me, or is `Marsaglia.createRandomized` never defined?

**Comment by Willard21** [comment]
Ah yeah, you're right. I never used it without a seed though, so it was never called.

**Comment by 00ff0000red** [comment]
> ...so it was never called.

I scanned through the code earlier and saw the same, so can the presence of a seed be made into an assertion, and the method call removed? Or should someone check the source library?

> That Marsaglia class, and both noise functions were copied from libraries, so I didn't write them myself.

I know, the comments had reference links, I checked them myself.
Still changed up their old code though.

Also, when you have the time, check the commits,if there's anything you dislike, tell me, I'll fix it.

I'm thinking that I'll go one-thousand lines per PR, so probably 6 PRs.

After that, I'll try to make algorithmic changes and help add new features.

**Comment by Willard21** [comment]
Everything random has to be fully reproducible, so it should never use an unseeded generator. So yes, the method call can be removed. For fully randomized, I'd just use `Math.random()`.

I noticed you changed the logic for default values in the blockData. Shadows are supposed to default to `true`, since all opaque blocks have them. And I personally find
```js
data.lightLevel = data.lightLevel || 0
```
Much more readable than
```js
data.lightLevel = "lightLevel" in data
	? data.lightLevel
	: 0;
```
The `||` syntax only breaks when a falsey value is possible and different than the default. ES2020 added the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) to solve that problem, but it's too new of a feature to use yet. However I believe using `||` syntax for default values is standard enough that they added a new operator just to make it work better. But if you really want to change it, at least make all the defaults use the same logic and syntax for consistency, otherwise it's not helping anything to change it.

> // nothing in this scope makes sense without comments

It's a hash function, so it just scrambles bits and spits out a new number. Not much else to say about it. It's an implementation of the xxHash algorithm, and it's used for tree placement.

**Comment by 00ff0000red** [comment]
> I noticed you changed the logic for default values in the blockData. Shadows are supposed to default to `true`, since all opaque blocks have them.

Yes, that part of the code is the only part that I likely changed the logic of.
I'll just revert it.

> And I personally find
> 
> ```js
> data.lightLevel = data.lightLevel || 0
> ```
> 
> Much more readable than
> 
> ```js
> data.lightLevel = "lightLevel" in data
> 	? data.lightLevel
> 	: 0;
> ```

Sorry, I have a strong tendency to avoid property lookups on non-existent properties. As stated, I'll just leave it as it was.

> The `||` syntax only breaks when a falsey value is possible and different than the default.

This is why I tend to avoid non-boolean boolean operators (`||`, `&&`), JS is a very weakly typed language.

> ES2020 added the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) to solve that problem, but it's too new of a feature to use yet.

No need to inform me of the newest features, I live on ES11, ESNext, and am always using the *most* bleeding edge, experimental technologies and JS syntax before they come out. I regularly use Chrome Beta with expirirmental flags and I'm always watching TC39 and ECMA-262 for anything new.
I'm always trying to get my hands on the newest APIs and whatnot too. Ex: [Project Fugu](https://javascript-conference.com/blog/making-the-web-more-powerful-with-project-fugu/), [CSS Houdini](https://developer.mozilla.org/en-US/docs/Web/Houdini), [WeakRefs](https://github.com/tc39/proposal-weakrefs), [FinalizationRegistries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry), and [anything new coming to Wasm](https://github.com/WebAssembly/proposals).
Simply put: there's nothing, old or new, about any web tech, that you could tell me, that I don't already know about.

> However I believe using `||` syntax for default values is standard enough that they added a new operator...

They actually also added compound assignment operators for this too...
```js
> data.lightLevel ||= 0;
```

But, like `??`, still too new to use here, maybe give it another year.

> > // nothing in this scope makes sense without comments
> 
> It's a hash function, so it just scrambles bits and spits out a new number. Not much else to say about it. It's an implementation of the xxHash algorithm, and it's used for tree placement.

Literally, just saying that it came from `xxHash` helps a lot. There's a lot of hash functions out there, some are less than ~5 lines, others are massive. I'll leave a comment near it.

**Comment by Phi-001** [comment]
According to [Can I use...](https://caniuse.com/?search=Nullish%20coalescing%20operator) most desktop browsers support nullish coalescing operator. 
> Simply put: there's nothing, old or new, about any web tech, that you could tell me, that I don't already know about.

Just curious. Do you know about WebGPU?

**Comment by 00ff0000red** [comment]
> Just curious. Do you know about WebGPU?

I was just looking into it more yesterday.
I dislike its API, since it's *intended* for use by JS, instead of Wasm, which it seems like a perfect fit for. They're both made for performance, and both use bytecode, but JS is still the loader, so there will have to be a lot of JS gluing everything together.

Both were made for use by native code developers too. But then again, Wasm should be getting a major update; by the end of next year I won't care, and I won't need to use JS for web dev anymore, since Wasm will have full JS interfacing capabilities.

**Comment by Phi-001** [comment]
Well, even if Wasm gets a major update, you still probably need to use JS since you have to access API to do a lot of stuff such as using GPU, connecting to a server, and more.

**Comment by 00ff0000red** [comment]
> Well, even if Wasm gets a major update, you still probably need to use JS since you have to access API to do a lot of stuff such as using GPU, connecting to a server, and more.

Nope, Wasm will have access to structs, and everything that WebIDL needs. I could call `fetch`, and then call `Promise#then`, all from Wasm, w/o JS interop.

Right now, I can only pass around values, and I can create objects and manipulate them by importing `Object`, `Array`, and `Reflect`, but it's hacky, very hacky. And inefficient; lots of code bloat and slow function calls.

**Comment by Phi-001** [comment]
Nice :)

**Comment by 00ff0000red** [comment]
This was already a lot and I stopped at line 1000.

**Pull request merged**
