### PR TITLE
add dist to gitignore because it is commiting too much changes

### PR DESCRIPTION
**Pull request by Phi-001**
in the title. also this is test of new extension that i installed which is i can create breanches from vscode.

### CODE REVIEW

**Comment by Phi-001** [comment]
apparently i can comment too. this is pretty amazing

**Comment by Willard21** [comment]
I'm not sure it's a good idea. While it would prevent the n00bz from plagiarizing it since they wouldn't be able to figure out how to run Node on Windows, it would also prevent me from deploying it automatically to GitHub Pages.

**Comment by Phi-001** [comment]
Oh true. I think I can use GitHub Actions to deploy it automatically.

**Comment by Phi-001** [comment]
Oh wait, but then you need to create a new branch or something. Was there a way to disable git on specific branches? IDK If it doesn't I'll close this one.

**Comment by Phi-001** [comment]
Did some googling and there doesn't seem to be a way so I'm gonna close it.

**Comment by bhavjitChauhan** [comment]
A simple way I've seen it done is with a separate branch (`live`, `production`, version number, etc.) that has a different `.gitignore` file with an optional release script to automate things.

Alternatively, as @Phi-001 said, you can use a GitHub Action that runs on push:
 - https://github.com/marketplace/actions/github-pages-action
 - https://github.com/marketplace/actions/deploy-to-github-pages

**Pull request closed without merging**
