### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by 00ff0000red**
This PR makes the following changes:
* Reformats HTML and (barely) changes the GLSL.
* Adds a few HTML attributes, ex: style[type], html[lang].
* Moves all inline CSS into the style element.
* Moderately de-duplicates the CSS.
* Changes the saving mechanism.
  It now uses a query string instead; users will be able to share their saves by simply sharing their URL, linking back to the original game, while keeping their save.
  If there are any downsides to this, please voice your concern(s).
  Otherwise, the JS is left the same.
* Moves the `<style>` to the `<head>`

Just a warning: the difference is massive because I had indented the... entire document, if it's slow to load, I'd recommend just looking at the results.

### CODE REVIEW

**Comment by Phi-001** [comment]
URL cannot be larger than 2000 characters in order for browser to able to parse it. There for it cannot save large world.

**Comment by 00ff0000red** [comment]
> [URL cannot be larger than 2000 characters](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) in order for browser to able to parse it. There for it cannot save large world.

How often does this generate URLs longer than that?

**Comment by Phi-001** [comment]
I'm not sure. Random one that I found by looking at spin-offs of the project was 610103.

**Comment by 00ff0000red** [comment]
> ...I found by looking at spin-offs of the project was 610103.

Dang, okay, I could create a simple, efficient string compressor, but eh, I'll just revert that part.

**Comment by theshinramen** [comment]
> How often does this generate URLs longer than that?

If I am not mistaken, to put it simply, the larger the world gets (like placing/breaking blocks and generating chunks), the longer the string gets.

**Comment by Phi-001** [comment]
Even the super simple example one is length of 612.

**Comment by 00ff0000red** [comment]
Also, there's a discrepancy between the versions of MineKhan, are we at 0.7.0 (here), or 0.7.1 ([Repl](https://repl.it/@Willard21/MineKhan))?

**Comment by Phi-001** [comment]
I'm pretty sure there's no difference between those, but I might be wrong tho.

**Comment by 00ff0000red** [comment]
> I'm pretty sure there's no difference between those, but I might be wrong tho.

Turns the one here (0.7.0) is more up-to-date.

Also, I've reverted the URL saving mechanism.

**Comment by Willard21** [comment]
Yeah I just forgot to commit the version change before copy/pasting it into KA and repl. The code is basically the same other than a comment or 2.

> I had indented the... entire document
I've written like 500 lines of code since the last commit since I'm adding lighting. Document-wide changes like that won't merge. I know the JS isn't indented properly relative to the surrounding HTML, but I figured it doesn't matter since JS and HTML are clearly different languages, and it saves like 18,000 tabs, which makes the code a little more readable.

Is there any chance you can join the Discord server so we can discuss changes before making them? If not, you should open an issue describing what you'd like to change and why, so that I can give feedback _before_ you spend the time working on it. I don't like telling people to throw away their code, but I kinda have to when you open PRs unexpectedly.

**Comment by 00ff0000red** [comment]
> I've written like 500 lines of code since the last commit since I'm adding lighting. Document-wide changes like that won't merge. I know the JS isn't indented properly relative to the surrounding HTML, but I figured it doesn't matter since JS and HTML are clearly different languages, and it saves like 18,000 tabs, which makes the code a little more readable.

Well, the HTML document itself wasn't even indented relative to other parts of itself.

> Is there any chance you can join the Discord server so we can discuss changes before making them?

I don't have a Discord account, and would rather not join.

> If not, you should open an issue describing what you'd like to change and why, so that I can give feedback _before_ you spend the time working on it.

This, on the other hand, I can do.

> I don't like telling people to throw away their code, but I kinda have to when you open PRs unexpectedly.

Hmm... I'm not sure why it has to go to *waste*, if anything, It could be dedented.

The PR can be split into two parts:
* indents the JS
* changes the HTML/CSS/GLSL
If you're about to merge a JS update, then why couldn't the HTML/CSS be updated from here?

**Comment by Willard21** [comment]
Yeah the HTML and CSS changes are fine. But I definitely don't like the JS being indented that much, since the code is basically starting in the middle of the editor lol.
image

**Pull request closed without merging**
